### PR TITLE
Add support for plain objects as scope

### LINKED ISSUE #97: Cannot use non-eloquent objects as scope
### Pennant Version

1.7.0

### Laravel Version

10.15.0

### PHP Version

8.1.23

### Database Driver & Version

_No response_

### Description

**Problem**

I'm currently using laravel without eloquent, and I'm trying to use simple user object as scope. Data to this object are loaded from auth API as I'm using service oriented architecture . When I try to use that object as scope I'm getting an exception `Unable to serialize the feature scope to a string. You should implement the FeatureScopeable contract.`, so I've implemented this interface to my object but basically return type of that method must be null|int|string|Model or I'll still get said exception from `\Laravel\Pennant\FeatureManager::serializeScope`. So I had to change my implementation to return just userId . But now my feature resolvers are getting just that userId as scope which means I have to again get user from my auth service based on its id.

**Expected behaviour**

I want it to work like it works with eloquent models. So you can pass object as scope and it will get serialized to string for purpose of serialization scope for storage.

**Proposed solution**

At first I thought that we can add new arm to match in serializeScope() something like this 
`$scope instanceof \Laravel\Pennant\Contracts\FeatureScopeable => $scope->toFeatureIdentifier()` but then I've realised that this method may not return string and looking further into the code it could break some things. So as an alternative to this we could create new interface to serve this purpose to create identifier for serialization. Then you can implement it at any object and you can keep your object as scope and serialization would also work. 

### Steps To Reproduce

Create any POPO object and try to use it as a scope, at first you will get exception to use FeatureScopeable and when you will implement it you will still be getting exceptions if your return value won't be null|int|string|Model

### PR DESCRIPTION
**Pull request by jkatruska**
Fixes https://github.com/laravel/pennant/issues/97

### CODE REVIEW

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Comment by jkatruska** [comment]
Hi @taylorotwell, thank you for your response. 

I still think this is a bug because according to the [documentation](https://laravel.com/docs/11.x/pennant#identifying-scope) `Pennant's built-in array and database storage drivers know how to properly store scope identifiers for all PHP data types as well as Eloquent models.` you should be able to use any data type as a scope, but as I mentioned in issue https://github.com/laravel/pennant/issues/97, only null|int|string|Model are valid scopes.

**Comment by timacdonald** [comment]
Please see my comment: https://github.com/laravel/pennant/issues/97#issuecomment-2031011469

**Comment by denisvanmorgan** [comment]
hi, any chance this gets more attention? IMO the proposed solution is more robust, without need to fetch user multiple times if you don't use eloquent model. not every app is necessarily using DB, e.g. BFF in microservice architecture, etc.

**Pull request closed without merging**
